import { formOfPlayersOnClay } from './atp-form-on-clay.js';
import { formOfPlayersOnHO } from './atp-form-on-out-hard.js';
import { formOfPlayersOnHI } from './atp-form-on-ind-hard.js';

const homeData = {
  name: 'Alcaraz C.',
  slug: 'alcaraz-carlos',
  shortName: 'Alcaraz C.',
  gender: 'M',
  sport: {
    name: 'Tennis',
    slug: 'tennis',
    id: 5,
  },
  category: {
    name: 'ATP',
    slug: 'atp',
    sport: {
      name: 'Tennis',
      slug: 'tennis',
      id: 5,
    },
    id: 3,
    flag: 'atp',
  },
  tournament: {
    name: 'French Open, Paris, France',
    slug: 'french-open-paris-france',
    category: {
      name: 'ATP',
      slug: 'atp',
      sport: {
        name: 'Tennis',
        slug: 'tennis',
        id: 5,
      },
      id: 3,
      flag: 'atp',
    },
    uniqueTournament: {
      name: 'Roland Garros',
      slug: 'roland-garros',
      category: {
        name: 'ATP',
        slug: 'atp',
        sport: {
          name: 'Tennis',
          slug: 'tennis',
          id: 5,
        },
        id: 3,
        flag: 'atp',
      },
      userCount: 47848,
      id: 2480,
      country: {},
      hasPerformanceGraphFeature: false,
      displayInverseHomeAwayTeams: false,
    },
    priority: 0,
    id: 93468,
  },
  userCount: 82998,
  playerTeamInfo: {
    residence: 'El Palmar, Murcia, Spain',
    birthplace: 'El Palmar, Murcia, Spain',
    height: 1.83,
    weight: 68,
    plays: 'right-handed',
    turnedPro: '2018',
    prizeCurrent: 2031660,
    prizeTotal: 11889696,
    id: 3111,
    birthDateTimestamp: 1052092800,
    prizeCurrentRaw: {
      value: 2031660,
      currency: 'EUR',
    },
    prizeTotalRaw: {
      value: 11889696,
      currency: 'EUR',
    },
    currentRanking: 2,
  },
  nameCode: 'ALC',
  ranking: 2,
  disabled: false,
  national: false,
  type: 1,
  id: 275923,
  country: {
    alpha2: 'ES',
    name: 'Spain',
  },
  fullName: 'Alcaraz, Carlos',
  teamColors: {
    primary: '#52b030',
    secondary: '#52b030',
    text: '#ffffff',
  },
  nearEvents: {
    previousEvent: {
      firstToServe: 1,
      homeTeamSeed: '1',
      awayTeamSeed: '10',
      tournament: {
        name: 'Madrid, Spain',
        slug: 'madrid-spain',
        category: {
          name: 'ATP',
          slug: 'atp',
          sport: {
            name: 'Tennis',
            slug: 'tennis',
            id: 5,
          },
          id: 3,
          flag: 'atp',
        },
        uniqueTournament: {
          name: 'Madrid Open',
          slug: 'madrid-open',
          category: {
            name: 'ATP',
            slug: 'atp',
            sport: {
              name: 'Tennis',
              slug: 'tennis',
              id: 5,
            },
            id: 3,
            flag: 'atp',
          },
          userCount: 10470,
          groundType: 'Red clay',
          id: 2374,
          hasEventPlayerStatistics: false,
          crowdsourcingEnabled: false,
          hasPerformanceGraphFeature: false,
          displayInverseHomeAwayTeams: false,
        },
        priority: 0,
        id: 113487,
      },
      roundInfo: {
        round: 27,
        name: 'Quarterfinal',
        slug: 'quarterfinal',
        cupRoundType: 4,
      },
      customId: 'FbLsytkc',
      status: {
        code: 100,
        description: 'Ended',
        type: 'finished',
      },
      winnerCode: 1,
      homeTeam: {
        name: 'Alcaraz C.',
        slug: 'alcaraz-carlos',
        shortName: 'Alcaraz C.',
        gender: 'M',
        sport: {
          name: 'Tennis',
          slug: 'tennis',
          id: 5,
        },
        userCount: 82998,
        playerTeamInfo: {
          id: 3111,
        },
        nameCode: 'ALC',
        ranking: 2,
        disabled: false,
        national: false,
        type: 1,
        id: 275923,
        subTeams: [],
        teamColors: {
          primary: '#52b030',
          secondary: '#52b030',
          text: '#ffffff',
        },
      },
      awayTeam: {
        name: 'Khachanov K.',
        slug: 'khachanov-karen',
        shortName: 'Khachanov K.',
        gender: 'M',
        sport: {
          name: 'Tennis',
          slug: 'tennis',
          id: 5,
        },
        userCount: 11954,
        playerTeamInfo: {
          id: 12,
        },
        nameCode: 'KHA',
        ranking: 12,
        disabled: false,
        national: false,
        type: 1,
        id: 90080,
        subTeams: [],
        teamColors: {
          primary: '#52b030',
          secondary: '#52b030',
          text: '#ffffff',
        },
      },
      homeScore: {
        current: 2,
        display: 2,
        period1: 6,
        period2: 7,
        point: '40',
        normaltime: 2,
      },
      awayScore: {
        current: 0,
        display: 0,
        period1: 4,
        period2: 5,
        point: '30',
        normaltime: 0,
      },
      time: {
        period1: 2949,
        period2: 3689,
        currentPeriodStartTimestamp: 1683126084,
      },
      changes: {
        changes: ['time.currentPeriodStart', 'time.period2'],
        changeTimestamp: 1683129796,
      },
      hasGlobalHighlights: true,
      id: 11225327,
      startTimestamp: 1683122400,
      slug: 'khachanov-alcaraz',
      periods: {
        point: 'Game',
        current: 'Match',
        period1: '1st set',
        period2: '2nd set',
        period3: '3rd set',
        period4: '4th set',
        period5: '5th set',
      },
      finalResultOnly: false,
      groundType: 'Red clay',
    },
    nextEvent: {
      homeTeamSeed: '1',
      awayTeamSeed: '17',
      tournament: {
        name: 'Madrid, Spain',
        slug: 'madrid-spain',
        category: {
          name: 'ATP',
          slug: 'atp',
          sport: {
            name: 'Tennis',
            slug: 'tennis',
            id: 5,
          },
          id: 3,
          flag: 'atp',
        },
        uniqueTournament: {
          name: 'Madrid Open',
          slug: 'madrid-open',
          category: {
            name: 'ATP',
            slug: 'atp',
            sport: {
              name: 'Tennis',
              slug: 'tennis',
              id: 5,
            },
            id: 3,
            flag: 'atp',
          },
          userCount: 10470,
          groundType: 'Red clay',
          id: 2374,
          hasEventPlayerStatistics: false,
          crowdsourcingEnabled: false,
          hasPerformanceGraphFeature: false,
          displayInverseHomeAwayTeams: false,
        },
        priority: 0,
        id: 113487,
      },
      roundInfo: {
        round: 28,
        name: 'Semifinal',
        slug: 'semifinal',
        cupRoundType: 2,
      },
      customId: 'FQAsytkc',
      status: {
        code: 0,
        description: 'Not started',
        type: 'notstarted',
      },
      winnerCode: 0,
      homeTeam: {
        name: 'Alcaraz C.',
        slug: 'alcaraz-carlos',
        shortName: 'Alcaraz C.',
        gender: 'M',
        sport: {
          name: 'Tennis',
          slug: 'tennis',
          id: 5,
        },
        userCount: 82998,
        playerTeamInfo: {
          id: 3111,
        },
        nameCode: 'ALC',
        ranking: 2,
        disabled: false,
        national: false,
        type: 1,
        id: 275923,
        subTeams: [],
        teamColors: {
          primary: '#52b030',
          secondary: '#52b030',
          text: '#ffffff',
        },
      },
      awayTeam: {
        name: 'Ćorić B.',
        slug: 'coric-borna',
        shortName: 'Ćorić B.',
        gender: 'M',
        sport: {
          name: 'Tennis',
          slug: 'tennis',
          id: 5,
        },
        userCount: 12293,
        playerTeamInfo: {
          id: 13,
        },
        nameCode: 'COR',
        ranking: 20,
        disabled: false,
        national: false,
        type: 1,
        id: 64580,
        subTeams: [],
        teamColors: {
          primary: '#52b030',
          secondary: '#52b030',
          text: '#ffffff',
        },
      },
      homeScore: {},
      awayScore: {},
      time: {},
      changes: {
        changeTimestamp: 0,
      },
      hasGlobalHighlights: false,
      id: 11225315,
      startTimestamp: 1683295200,
      slug: 'coric-alcaraz',
      periods: {
        point: 'Game',
        current: 'Match',
        period1: '1st set',
        period2: '2nd set',
        period3: '3rd set',
        period4: '4th set',
        period5: '5th set',
      },
      finalResultOnly: false,
      groundType: 'Red clay',
    },
  },
  teamRankings: [
    {
      position: 2,
      rankingTypeName: 'ATP Rankings Live',
      rankingTypeSlug: 'atp-rankings-live',
      gender: 'M',
    },
    {
      position: 2,
      rankingTypeName: 'ATP Rankings',
      rankingTypeSlug: 'atp-rankings',
      gender: 'M',
    },
  ],
  properName: 'Carlos Alcaraz',
  firstName: 'Carlos',
  lastName: 'Alcaraz',
  recentMatches: [
    11133932, 11204457, 11204442, 11204453, 11204438, 11204460, 11225157,
    11225123, 11225333, 11225327,
  ],
  hardcourtOutdoorStats: {
    totalMatches: 11,
    won: 10,
    lost: 1,
    winPerc: 90.91,
    titles: [
      {
        titleId: 2487,
        titleSlug: 'atp-indian-wells',
        titleName: 'Indian Wells',
      },
    ],
    acesTotal: 32,
    acesAvg: 2.91,
    doubleFaultsTotal: 20,
    doubleFaultsAvg: 1.82,
    breakPointsTotal: 33,
    breaksConvAvg: 3,
    firstServeTotal: 650,
    firstServeIn: 440,
    firstServePerc: 69,
    secondServeTotal: 210,
    secondServeIn: 190,
    secondServePerc: 93.27,
    firstServePointsTotal: 440,
    firstServePointsWon: 329,
    firstServePointsPerc: 76.18,
    secondServePointsTotal: 210,
    secondServePointsWon: 120,
    secondServePointsPerc: 60.27,
    breakPointsAgainst: 31,
    breakPointsSaved: 21,
    breakPointsSavedPerc: 67.74,
    tieBreaks: 4,
  },
  hardcourtIndoorStats: {
    totalMatches: 0,
    won: 0,
    lost: 0,
    winPerc: 0,
    titles: [],
    acesTotal: 0,
    acesAvg: 0,
    doubleFaultsTotal: 0,
    doubleFaultsAvg: 0,
    breakPointsTotal: 0,
    breaksConvAvg: 0,
    firstServeTotal: 0,
    firstServeIn: 0,
    firstServePerc: 0,
    secondServeTotal: 0,
    secondServeIn: 0,
    secondServePerc: 0,
    firstServePointsTotal: 0,
    firstServePointsWon: 0,
    firstServePointsPerc: 0,
    secondServePointsTotal: 0,
    secondServePointsWon: 0,
    secondServePointsPerc: 0,
    breakPointsAgainst: 0,
    breakPointsSaved: 0,
    breakPointsSavedPerc: 0,
    tieBreaks: 0,
  },
  redClayStats: {
    totalMatches: 18,
    won: 17,
    lost: 1,
    winPerc: 94.44,
    titles: [
      {
        titleId: 2383,
        titleSlug: 'atp-buenos-aires',
        titleName: 'Buenos Aires',
      },
      {
        titleId: 2407,
        titleSlug: 'atp-barcelona',
        titleName: 'Barcelona',
      },
    ],
    acesTotal: 61,
    acesAvg: 3.39,
    doubleFaultsTotal: 30,
    doubleFaultsAvg: 1.67,
    breakPointsTotal: 80,
    breaksConvAvg: 4.44,
    firstServeTotal: 1235,
    firstServeIn: 905,
    firstServePerc: 73.61,
    secondServeTotal: 330,
    secondServeIn: 300,
    secondServePerc: 82.72,
    firstServePointsTotal: 905,
    firstServePointsWon: 610,
    firstServePointsPerc: 69.94,
    secondServePointsTotal: 330,
    secondServePointsWon: 194,
    secondServePointsPerc: 84.44,
    breakPointsAgainst: 98,
    breakPointsSaved: 63,
    breakPointsSavedPerc: 64.29,
    tieBreaks: 2,
  },
  grassStats: {
    totalMatches: 0,
    won: 0,
    lost: 0,
    winPerc: 0,
    titles: [],
    acesTotal: 0,
    acesAvg: 0,
    doubleFaultsTotal: 0,
    doubleFaultsAvg: 0,
    breakPointsTotal: 0,
    breaksConvAvg: 0,
    firstServeTotal: 0,
    firstServeIn: 0,
    firstServePerc: 0,
    secondServeTotal: 0,
    secondServeIn: 0,
    secondServePerc: 0,
    firstServePointsTotal: 0,
    firstServePointsWon: 0,
    firstServePointsPerc: 0,
    secondServePointsTotal: 0,
    secondServePointsWon: 0,
    secondServePointsPerc: 0,
    breakPointsAgainst: 0,
    breakPointsSaved: 0,
    breakPointsSavedPerc: 0,
    tieBreaks: 0,
  },
  playerSlug: 'carlos-alcaraz',
  dbLocation:
    '/Users/radulazar1/OneDrive/spt/db/tennis/teams/c/ca/275923/275923.json',
  dbFolder: '/Users/radulazar1/OneDrive/spt/db/tennis/teams/c/ca/275923',
};

const awayData = {
  name: 'Chakravarthi C.',
  slug: 'chakravarthi-caleb',
  shortName: 'Chakravarthi C.',
  gender: 'M',
  sport: {
    name: 'Tennis',
    slug: 'tennis',
    id: 5,
  },
  category: {
    name: 'ITF Men',
    slug: 'itf-men',
    sport: {
      name: 'Tennis',
      slug: 'tennis',
      id: 5,
    },
    id: 785,
    flag: 'itf-men',
  },
  tournament: {
    name: 'Dallas, USA',
    slug: 'dallas-usa',
    category: {
      name: 'ATP',
      slug: 'atp',
      sport: {
        name: 'Tennis',
        slug: 'tennis',
        id: 5,
      },
      id: 3,
      flag: 'atp',
    },
    uniqueTournament: {
      name: 'Dallas',
      slug: 'dallas',
      category: {
        name: 'ATP',
        slug: 'atp',
        sport: {
          name: 'Tennis',
          slug: 'tennis',
          id: 5,
        },
        id: 3,
        flag: 'atp',
      },
      userCount: 905,
      id: 18377,
      country: {},
      hasPerformanceGraphFeature: false,
      displayInverseHomeAwayTeams: false,
    },
    priority: 0,
    id: 96883,
  },
  userCount: 5,
  nameCode: 'CHA',
  national: false,
  type: 1,
  id: 232568,
  country: {
    alpha2: 'US',
    name: 'USA',
  },
  fullName: 'Chakravarthi, Caleb',
  teamColors: {
    primary: '#52b030',
    secondary: '#52b030',
    text: '#ffffff',
  },
  nearEvents: {
    previousEvent: {
      firstToServe: 2,
      tournament: {
        name: 'Fountain Valley, Doubles, 2022 USA F20, Doubles',
        slug: 'fountain-valley-doubles-2022-usa-f20-doubles',
        category: {
          name: 'ITF Men',
          slug: 'itf-men',
          sport: {
            name: 'Tennis',
            slug: 'tennis',
            id: 5,
          },
          id: 785,
          flag: 'itf-men',
        },
        uniqueTournament: {
          name: 'ITF USA F20, Men Doubles',
          slug: 'itf-usa-f20-men-doubles',
          category: {
            name: 'ITF Men',
            slug: 'itf-men',
            sport: {
              name: 'Tennis',
              slug: 'tennis',
              id: 5,
            },
            id: 785,
            flag: 'itf-men',
          },
          userCount: 1,
          groundType: 'Hardcourt outdoor',
          id: 12508,
          hasEventPlayerStatistics: false,
          crowdsourcingEnabled: false,
          hasPerformanceGraphFeature: false,
          displayInverseHomeAwayTeams: false,
        },
        priority: 0,
        id: 103579,
      },
      roundInfo: {
        round: 8,
        name: 'Round of 16',
        slug: 'round-of-16',
        cupRoundType: 8,
      },
      customId: 'xmtdsJAtd',
      status: {
        code: 100,
        description: 'Ended',
        type: 'finished',
      },
      winnerCode: 2,
      homeTeam: {
        name: 'Chakravarthi C / Scott F',
        slug: 'chakravarthi-c-scott-f',
        shortName: 'Chakravarthi C / Scott F',
        gender: 'M',
        sport: {
          name: 'Tennis',
          slug: 'tennis',
          id: 5,
        },
        userCount: 1,
        nameCode: 'C/S',
        national: false,
        type: 2,
        id: 421284,
        subTeams: [
          {
            name: 'Chakravarthi C.',
            slug: 'chakravarthi-caleb',
            shortName: 'Chakravarthi C.',
            gender: 'M',
            sport: {
              name: 'Tennis',
              slug: 'tennis',
              id: 5,
            },
            userCount: 5,
            nameCode: 'CHA',
            national: false,
            type: 1,
            id: 232568,
            subTeams: [],
            teamColors: {
              primary: '#52b030',
              secondary: '#52b030',
              text: '#ffffff',
            },
          },
          {
            name: 'Scott F.',
            slug: 'scott-fletcher',
            shortName: 'Scott F.',
            gender: 'M',
            sport: {
              name: 'Tennis',
              slug: 'tennis',
              id: 5,
            },
            userCount: 34,
            playerTeamInfo: {
              id: 4540,
            },
            nameCode: 'SCO',
            ranking: 1421,
            national: false,
            type: 1,
            id: 213377,
            subTeams: [],
            teamColors: {
              primary: '#52b030',
              secondary: '#52b030',
              text: '#ffffff',
            },
          },
        ],
        teamColors: {
          primary: '#52b030',
          secondary: '#52b030',
          text: '#ffffff',
        },
      },
      awayTeam: {
        name: 'Hsu J C E / Lee K-Y',
        slug: 'hsu-j-c-e-lee-k-y',
        shortName: 'Hsu J C E / Lee K-Y',
        gender: 'M',
        sport: {
          name: 'Tennis',
          slug: 'tennis',
          id: 5,
        },
        userCount: 0,
        nameCode: 'HJC',
        national: false,
        type: 2,
        id: 420622,
        subTeams: [
          {
            name: 'Hsu J.',
            slug: 'hsu-jeffrey-chuan-en',
            shortName: 'Hsu J.',
            gender: 'M',
            sport: {
              name: 'Tennis',
              slug: 'tennis',
              id: 5,
            },
            userCount: 9,
            playerTeamInfo: {
              id: 5579,
            },
            nameCode: 'HSU',
            ranking: 1717,
            national: false,
            type: 1,
            id: 171072,
            subTeams: [],
            teamColors: {
              primary: '#52b030',
              secondary: '#52b030',
              text: '#ffffff',
            },
          },
          {
            name: 'Lee K.',
            slug: 'lee-kuan-yi',
            shortName: 'Lee K.',
            gender: 'M',
            sport: {
              name: 'Tennis',
              slug: 'tennis',
              id: 5,
            },
            userCount: 36,
            playerTeamInfo: {
              id: 2401,
            },
            nameCode: 'LEE',
            ranking: 1410,
            national: false,
            type: 1,
            id: 169596,
            subTeams: [],
            teamColors: {
              primary: '#52b030',
              secondary: '#52b030',
              text: '#ffffff',
            },
          },
        ],
        teamColors: {
          primary: '#52b030',
          secondary: '#52b030',
          text: '#ffffff',
        },
      },
      homeScore: {
        current: 0,
        display: 0,
        period1: 5,
        period2: 2,
        point: '15',
        normaltime: 0,
      },
      awayScore: {
        current: 2,
        display: 2,
        period1: 7,
        period2: 6,
        point: '40',
        normaltime: 2,
      },
      time: {
        period1: 2576,
        period2: 2048,
        currentPeriodStartTimestamp: 1657058880,
      },
      changes: {
        changes: ['time.currentPeriodStart', 'time.period2'],
        changeTimestamp: 1657060957,
      },
      hasGlobalHighlights: false,
      id: 10434915,
      startTimestamp: 1657053900,
      slug: 'chakravarthi-scott-hsuc-lee-k-y',
      periods: {
        point: 'Game',
        current: 'Match',
        period1: '1st set',
        period2: '2nd set',
        period3: '3rd set',
        period4: '4th set',
        period5: '5th set',
      },
      finalResultOnly: false,
      groundType: 'Hardcourt outdoor',
    },
    nextEvent: null,
  },
  properName: 'Caleb Chakravarthi',
  firstName: 'Caleb',
  lastName: 'Chakravarthi',
  recentMatches: [7643790, 7677289, 7852968, 8050421, 10121602],
  hardcourtOutdoorStats: {
    totalMatches: 8,
    won: 5,
    lost: 3,
    winPerc: 56,
    titles: [
      {
        titleId: 2383,
        titleSlug: 'atp-buenos-aires',
        titleName: 'Buenos Aires',
      },
      {
        titleId: 2407,
        titleSlug: 'atp-barcelona',
        titleName: 'Barcelona',
      },
    ],
    acesTotal: 0,
    acesAvg: 0,
    doubleFaultsTotal: 0,
    doubleFaultsAvg: 0,
    breakPointsTotal: 0,
    breaksConvAvg: 0,
    firstServeTotal: 0,
    firstServeIn: 0,
    firstServePerc: 0,
    secondServeTotal: 0,
    secondServeIn: 0,
    secondServePerc: 0,
    firstServePointsTotal: 0,
    firstServePointsWon: 0,
    firstServePointsPerc: 0,
    secondServePointsTotal: 0,
    secondServePointsWon: 0,
    secondServePointsPerc: 0,
    breakPointsAgainst: 0,
    breakPointsSaved: 0,
    breakPointsSavedPerc: 0,
    tieBreaks: 0,
  },
  hardcourtIndoorStats: {
    totalMatches: 7,
    won: 10,
    lost: 5,
    winPerc: 49,
    titles: [
      {
        titleId: 2383,
        titleSlug: 'atp-buenos-aires',
        titleName: 'Buenos Aires',
      },
      {
        titleId: 2407,
        titleSlug: 'atp-barcelona',
        titleName: 'Barcelona',
      },
    ],
    acesTotal: 0,
    acesAvg: 0,
    doubleFaultsTotal: 0,
    doubleFaultsAvg: 0,
    breakPointsTotal: 0,
    breaksConvAvg: 0,
    firstServeTotal: 0,
    firstServeIn: 0,
    firstServePerc: 0,
    secondServeTotal: 0,
    secondServeIn: 0,
    secondServePerc: 0,
    firstServePointsTotal: 0,
    firstServePointsWon: 0,
    firstServePointsPerc: 0,
    secondServePointsTotal: 0,
    secondServePointsWon: 0,
    secondServePointsPerc: 0,
    breakPointsAgainst: 0,
    breakPointsSaved: 0,
    breakPointsSavedPerc: 0,
    tieBreaks: 0,
  },
  redClayStats: {
    totalMatches: 0,
    won: 0,
    lost: 0,
    winPerc: 0,
    titles: [
      {
        titleId: 2383,
        titleSlug: 'atp-buenos-aires',
        titleName: 'Buenos Aires',
      },
      {
        titleId: 2407,
        titleSlug: 'atp-barcelona',
        titleName: 'Barcelona',
      },
    ],
    acesTotal: 0,
    acesAvg: 0,
    doubleFaultsTotal: 0,
    doubleFaultsAvg: 0,
    breakPointsTotal: 0,
    breaksConvAvg: 0,
    firstServeTotal: 0,
    firstServeIn: 0,
    firstServePerc: 0,
    secondServeTotal: 0,
    secondServeIn: 0,
    secondServePerc: 0,
    firstServePointsTotal: 0,
    firstServePointsWon: 0,
    firstServePointsPerc: 0,
    secondServePointsTotal: 0,
    secondServePointsWon: 0,
    secondServePointsPerc: 0,
    breakPointsAgainst: 0,
    breakPointsSaved: 0,
    breakPointsSavedPerc: 0,
    tieBreaks: 0,
  },
  grassStats: {
    totalMatches: 6,
    won: 3,
    lost: 3,
    winPerc: 72,
    titles: [
      {
        titleId: 2383,
        titleSlug: 'atp-buenos-aires',
        titleName: 'Buenos Aires',
      },
      {
        titleId: 2407,
        titleSlug: 'atp-barcelona',
        titleName: 'Barcelona',
      },
    ],
    acesTotal: 0,
    acesAvg: 0,
    doubleFaultsTotal: 0,
    doubleFaultsAvg: 0,
    breakPointsTotal: 0,
    breaksConvAvg: 0,
    firstServeTotal: 0,
    firstServeIn: 0,
    firstServePerc: 0,
    secondServeTotal: 0,
    secondServeIn: 0,
    secondServePerc: 0,
    firstServePointsTotal: 0,
    firstServePointsWon: 0,
    firstServePointsPerc: 0,
    secondServePointsTotal: 0,
    secondServePointsWon: 0,
    secondServePointsPerc: 0,
    breakPointsAgainst: 0,
    breakPointsSaved: 0,
    breakPointsSavedPerc: 0,
    tieBreaks: 0,
  },
  playerSlug: 'caleb-chakravarthi',
  dbLocation:
    '/Users/radulazar1/OneDrive/spt/db/tennis/teams/c/ca/232568/232568.json',
  dbFolder: '/Users/radulazar1/OneDrive/spt/db/tennis/teams/c/ca/232568',
};

const match = {
  groundType: 'Hardcourt indoor',
};

const res = formOfPlayersOnHI(match, homeData, awayData);

console.log(res);
